export const UI_COPY = {
  en: {
    navHome: 'Home',
    navQuick: 'Quick',
    navCalendar: 'Calendar',
    navMe: 'Me',
    loginTitle: 'CheckMate',
    loginTagline: 'Plan smarter, travel together.',
    signIn: 'Sign in',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm password',
    createAccount: 'Create account',
    pleaseWait: 'Please wait…',
    loginNeedCreds: 'Please enter username and password.',
    passwordTooShort: 'Password must be at least 6 characters.',
    passwordsNoMatch: 'Passwords do not match.',
    apiDown: 'Something went wrong. Is the API running?',
    usernameHint: '3–32 chars: lowercase letters, digits, underscore',
    passwordHintRegister: 'At least 6 characters',
    passwordHintLogin: '••••••••',
    passwordReenter: 'Re-enter password',
    greetingMorning: 'Good Morning,',
    greetingAfternoon: 'Good Afternoon,',
    greetingEvening: 'Good Evening,',
    whereToToday: 'Where to today?',
    now: 'Now',
    refreshWeather: 'Refresh weather',
    fullForecast: 'Full forecast',
    openMeteoHint: 'Open-Meteo live data · tap card for hourly & 7-day',
    quickScenarios: 'Quick Scenarios',
    quickScenariosHint: 'Open a preset packing list and start quickly.',
    quickScenariosEmpty: 'No quick scenarios right now',
    quickUseTemplate: 'Use template',
    quickExistingTitle: 'Existing quick scenarios',
    quickCategoryCommon: 'Common',
    quickCategorySports: 'Sports',
    quickCategoryOuting: 'Outing',
    quickCategoryFamily: 'Family',
    quickCategoryStudy: 'Study',
    myTrips: 'My Trips',
    calendarHint: 'Use calendar view to plan your trips by date.',
    calendarSelectedDateLabel: 'Selected date',
    calendarTripCount: 'Scheduled trips',
    calendarNoTrips: 'No scheduled trips on this date.',
    calendarCreateTripOnDate: 'Create trip on this date',
    calendarRescheduleBtn: 'Change time',
    calendarRescheduleTitle: 'Change trip time',
    tripPastDateBlocked: 'You cannot create a trip in the past.',
    myTripsEmptyTitle: 'No trips created yet',
    myTripsEmptyDesc: 'Create your first trip to see it here.',
    weatherSmartTipsTitle: 'Weather smart tips',
    weatherSmartTipsDesc: 'Based on UV, humidity, wind, and temperature.',
    weatherItemsLabel: 'items',
    weatherSmartNoExtra: 'No extra weather-specific items suggested right now.',
    weatherNoTripOption: 'Create a trip first',
    weatherAddBtn: 'Add to trip',
    weatherAddOk: 'Added weather tips to your trip.',
    weatherAddFail: 'Could not add right now.',
    weatherTipsExpand: 'Show',
    weatherTipsCollapse: 'Hide',
    fromUser: 'From',
    tripScheduledTag: 'Scheduled',
    calendarQuickAssignTitle: 'Quick assign date',
    calendarQuickAssignHint: 'Long press date selected',
    calendarNoDateYet: 'No date yet',
    calendarNoAssignableTrips: 'No editable trips available.',
    allSet: 'All Set!',
    packedMsg: 'Everything is packed.',
    enjoyMsg: 'Enjoy the sunshine and breeze today!',
    viewHistory: 'View history',
    backHome: "Let's Go",
    lastPacked: 'Last packed',
    aiImportTitle: 'Import From AI Suggestion',
    aiImportSelectedCount: 'selected',
    aiImportSelectAll: 'Select all',
    aiImportClear: 'Clear',
    aiImportMust: 'Must',
    aiImportNice: 'Nice',
    aiImportNewTripPlaceholder: 'New trip name',
    aiImportCreateBtn: 'Create trip with selected items',
    aiImportContinueToCreateBtn: 'Continue to create trip',
    aiImportNoEditableTrips: 'No editable trips',
    aiImportAddBtn: 'Add to existing',
    aiImportOpenTrips: 'Go to my Trips',
    aiImportCreatedOk: 'Created a new trip with {count} items.',
    aiImportAddedOk: 'Added {count} items to selected trip.',
    aiImportCreateFail: 'Could not create a trip right now.',
    aiImportAddFail: 'Could not add items right now.',
    askAnything: 'Ask me anything about packing…',
    assistantTitle: 'Packing assistant',
    assistantSmartHints: 'Smart hints',
    assistantThinking: 'Thinking…',
    assistantCurrentAi: 'Current AI: {name}.',
    assistantNoKeyHint: 'No AI keys configured on server. Showing offline suggestions only.',
    aiImportDefaultTripName: 'Trip from AI {date}',
    assistantOfflineFallbackHint: '— Offline fallback (cloud error: {hint})',
    title: 'Settings',
    accountCenter: 'Account center',
    signedIn: 'Signed in',
    edit: 'Edit',
    general: 'General',
    generalHint: 'Notifications, sounds, and location',
    personalization: 'Personalization',
    personalizationHint: 'Theme and appearance',
    accountSecurity: 'Account security',
    accountSecurityHint: 'Password and account safety',
    openSection: 'Open',
    loadingPrefs: 'Loading preferences…',
    notifications: 'Notifications',
    sounds: 'Sounds',
    autoLocation: 'Auto location',
    language: 'Language',
    langChinese: 'Chinese',
    langEnglish: 'English',
    darkMode: 'Dark mode',
    themeColor: 'Theme color',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    passwordMismatch: 'The two passwords do not match.',
    passwordUpdated: 'Password updated successfully.',
    passwordSaveError: 'Could not update password right now.',
    updatePassword: 'Update password',
    dangerous: 'Danger zone',
    deleteAccountHint: 'Deleting your account is irreversible.',
    deleteConfirmLabel: 'Type DELETE to confirm',
    deleteConfirmPlaceholder: 'DELETE',
    deleteMismatch: 'Confirmation text does not match.',
    deleteAccountButton: 'Delete account',
    serverStatus: 'Server status',
    serverOk: 'Online',
    serverFail: 'Offline',
    logOut: 'Log out',
    displayName: 'Display name',
    displayNameHint: 'Shown to your friends and in shared trips.',
    avatarStyle: 'Avatar style',
    placeholder: 'Enter display name',
    cancel: 'Cancel',
    save: 'Save',
    savingProfile: 'Saving…',
    displayNameSaveError: 'Could not save profile right now.',
    notifDenied: 'Notifications are blocked in your browser settings.',
    pickLanguage: 'Choose language',
    close: 'Close',
    weatherSourceFallback: 'System fallback',
    weatherSourceUnknown: 'Source unavailable',
    fetchingForecast: 'Fetching live forecast…',
    tapRefreshWeather: 'Tap refresh to load weather',
    weatherSummaryHighLow: 'High {max}° / Low {min}°',
    weatherSummaryRainChance: 'Rain chance {value}%',
    weatherSummaryWind: 'Wind {value} km/h',
    weatherSummaryHumidity: 'Humidity {value}%',
    weatherSummaryUv: 'UV {value}',
    weatherSummaryBasedOnForecast: 'Based on weather forecast',
    weatherTipsForDate: 'Tips for {date}',
    weatherTipMustPrefix: 'Must: ',
    weatherTipOptionalPrefix: 'Tip: ',
    createTripTitle: 'Create trip',
    tripNameLabel: 'Name',
    tripNamePlaceholder: 'e.g. Beach weekend trip…',
    tripDateTimeLabel: 'Departure date and time',
    tripDateStart: 'Departure',
    tripDateEnd: 'Return (optional)',
    tripEndBeforeStartError: 'Choose a departure time first; return cannot be before departure.',
    tripChecklistLabel: 'Checklist',
    tripMustBring: 'Must bring',
    tripOptional: 'Optional',
    tripAddMustPlaceholder: 'Add a must-bring item…',
    tripAddOptionalPlaceholder: 'Add an optional item…',
    detailEditItem: 'Edit item text',
    detailManageListHint: 'Add, edit, or remove items below.',
    tripItemsCount: '{count} items',
    tripStartPastError: 'Trip start time cannot be in the past.',
    commonCancel: 'Cancel',
    commonSave: 'Save',
    commonDelete: 'Delete',
    myLibraryTitle: 'Me',
    myLibrarySubtitle: 'Library',
    segmentTrips: 'Trips',
    segmentHistory: 'History',
    segmentFriends: 'Friends',
    yourTripsTitle: 'Your trips',
    newTripBtn: '+ New trip',
    select: 'Select',
    selectedCount: 'Selected {selected} / {total}',
    deleteSelected: 'Delete selected',
    deleteSelectedConfirmTitle: 'Delete selected trips?',
    deleteSelectedConfirmMsg: 'Delete {count} selected trips? This action cannot be undone.',
    deleteTripConfirmTitle: 'Delete this trip?',
    cannotUndo: 'This action cannot be undone.',
    createCustomTripTitle: 'Create a custom trip',
    createCustomTripDesc: 'Build your own packing list from scratch.',
    frequentlyUsed: 'Frequently used',
    noFrequentTrips: 'No frequent trips yet',
    noFrequentTripsDesc: 'Finish packing a few trips and your frequent ones will appear here.',
    clearAll: 'Clear all',
    clearHistoryTitle: 'Clear all history?',
    clearHistoryMsg: 'Delete all packing history on this account? This action cannot be undone.',
    noHistoryYet: 'No history yet',
    noHistoryHint: 'Finish packing a trip and it will appear here.',
    doneTag: 'Done',
    reuse: 'Reuse',
    deleteHistoryEntry: 'Delete history entry',
    friendsSectionTitle: 'Friends (Checkmate accounts)',
    friendsSectionHint: 'Enter their login username. They must accept before sharing lists.',
    enterUsername: 'Please enter a username.',
    requestSent: 'Request sent.',
    friendRequestSend: 'Send request',
    incomingRequestExists: 'They already sent you a request. You can accept it below.',
    requestFailed: 'Request failed.',
    lookingUp: 'Looking up…',
    noSuchUser: 'No such username found.',
    acceptPendingQuestion: 'Accept their pending request?',
    accept: 'Accept',
    incomingRequests: 'Incoming requests',
    decline: 'Decline',
    outgoingRequests: 'Waiting for response',
    friendsCount: 'Friends ({count})',
    noFriendsYet: 'No friends yet',
    friendLabel: 'friend',
    noFriendsHint: 'Send a request above. After acceptance, friends appear here.',
    online: 'Online',
    removeFriend: 'Remove friend',
    removeFriendTitle: 'Remove friend?',
    removeFriendHint: 'Removing ends sharing; assigned items return to you.',
    remove: 'Remove',
    pleaseWaitText: 'Please wait…',
    sharedBy: 'Shared by',
    assignItem: 'Assign item',
    packedProgress: 'Packed {checked} / {total}',
    assignHint: 'Tap the avatar beside an item to assign who packs it.',
    criticalLabel: 'Critical items',
    normalLabel: 'Other items',
    finishReady: 'All packed, ready to go!',
    finishNeedCritical: 'Please finish critical items first.',
    viewOnlyHint: 'Only the owner can check items. You are in read-only mode.',
    shareOnServer: 'Share on server',
    shareOnServerHint: 'Enter a friend\'s Checkmate username. They must accept friend request first.',
    shareAllowEditTitle: 'Allow editing',
    shareAllowEditHint: 'If enabled, they can edit items in this trip.',
    sharedWithTitle: 'Shared with',
    sharePermissionView: 'View only',
    sharePermissionEdit: 'Can edit',
    shareUsernamePlaceholder: 'e.g. alex_travels',
    checkingUsername: 'Checking username…',
    noAccountWithUsername: 'No account with this username.',
    yourFriends: 'Your friends',
    share: 'Share',
    couldNotShare: 'Could not share.',
    peopleOnThisList: 'People on this list',
    peopleOnThisListHint: 'Add friends to the trip, then assign items to them.',
    addFriendsFirst: 'Add friends in Me first, then come back.',
    add: 'Add',
    done: 'Done',
    whoPacksThis: 'Who packs this?',
    addPeopleBeforeAssign: 'Add members to this trip before assigning items.',
    revoke: 'Revoke',
    couldNotRevokeShare: 'Could not revoke sharing.',
    scenarioNotFound: 'Scenario not found. Please go back and try again.',
    goBack: 'Go back',
  },
  zh: {
    navHome: '首页',
    navQuick: '快捷',
    navCalendar: '日历',
    navMe: '我的',
    loginTitle: 'CheckMate',
    loginTagline: '规划更省心，出行更从容。',
    signIn: '登录',
    register: '注册',
    username: '用户名',
    password: '密码',
    confirmPassword: '确认密码',
    createAccount: '创建账号',
    pleaseWait: '请稍候…',
    loginNeedCreds: '请输入用户名和密码。',
    passwordTooShort: '密码至少 6 位。',
    passwordsNoMatch: '两次输入的密码不一致。',
    apiDown: '连接失败，请确认后端服务已启动。',
    usernameHint: '3–32 位：小写字母/数字/下划线',
    passwordHintRegister: '至少 6 位',
    passwordHintLogin: '••••••••',
    passwordReenter: '再次输入密码',
    greetingMorning: '早上好，',
    greetingAfternoon: '下午好，',
    greetingEvening: '晚上好，',
    whereToToday: '今天去哪儿？',
    now: '当前',
    refreshWeather: '刷新天气',
    fullForecast: '完整预报',
    openMeteoHint: 'Open-Meteo 实时天气 · 点击卡片查看逐小时和 7 日预报',
    quickScenarios: '快捷场景',
    quickScenariosHint: '选择一个预设场景，快速开始打包。',
    quickScenariosEmpty: '暂无可用的快捷场景',
    quickUseTemplate: '套用场景',
    quickExistingTitle: '已创建的快捷场景',
    quickCategoryCommon: '常用',
    quickCategorySports: '运动',
    quickCategoryOuting: '出行',
    quickCategoryFamily: '亲子',
    quickCategoryStudy: '校园',
    myTrips: '我的行程',
    calendarHint: '按日期查看和安排你的行程。',
    calendarSelectedDateLabel: '选择日期',
    calendarTripCount: '已安排的行程',
    calendarNoTrips: '该日期暂无行程安排。',
    calendarCreateTripOnDate: '在该日期创建行程',
    calendarRescheduleBtn: '修改时间',
    calendarRescheduleTitle: '修改行程时间',
    tripPastDateBlocked: '不能创建过去日期的行程。',
    myTripsEmptyTitle: '你还没有创建行程',
    myTripsEmptyDesc: '创建第一个行程后，就会显示在这里。',
    weatherSmartTipsTitle: '天气打包建议',
    weatherSmartTipsDesc: '根据紫外线、湿度、风速和温度智能生成。',
    weatherItemsLabel: '条',
    weatherSmartNoExtra: '当前没有额外的天气相关建议。',
    weatherNoTripOption: '请先创建一个行程',
    weatherAddBtn: '加入行程',
    weatherAddOk: '天气建议已加入行程。',
    weatherAddFail: '添加失败，请稍后重试。',
    weatherTipsExpand: '展开',
    weatherTipsCollapse: '收起',
    fromUser: '来自',
    tripScheduledTag: '已排期',
    calendarQuickAssignTitle: '快速设置日期',
    calendarQuickAssignHint: '已长按选择日期',
    calendarNoDateYet: '尚未设置日期',
    calendarNoAssignableTrips: '暂无可编辑的行程',
    allSet: '准备就绪！',
    packedMsg: '已全部打包完成。',
    enjoyMsg: '祝你一路顺风！',
    viewHistory: '查看历史',
    backHome: '回到首页',
    lastPacked: '最近完成',
    aiImportTitle: '从 AI 建议导入',
    aiImportSelectedCount: '已选',
    aiImportSelectAll: '全选',
    aiImportClear: '清空',
    aiImportMust: '必带',
    aiImportNice: '可选',
    aiImportNewTripPlaceholder: '新行程名称',
    aiImportCreateBtn: '新建行程并导入所选项',
    aiImportContinueToCreateBtn: '继续新建行程',
    aiImportNoEditableTrips: '暂无可编辑的行程',
    aiImportAddBtn: '添加到现有',
    aiImportOpenTrips: '前往我的行程',
    aiImportCreatedOk: '创建成功，已新建行程并导入 {count} 条。',
    aiImportAddedOk: '已成功导入 {count} 条到所选行程。',
    aiImportCreateFail: '创建失败，请稍后再试。',
    aiImportAddFail: '添加失败，请稍后再试。',
    weatherSourceFallback: '离线数据',
    weatherSourceUnknown: '数据源暂不可用',
    fetchingForecast: '正在获取实时天气…',
    tapRefreshWeather: '点击刷新获取天气',
    weatherSummaryHighLow: '最高 {max}° / 最低 {min}°',
    weatherSummaryRainChance: '降雨概率 {value}%',
    weatherSummaryWind: '风速 {value} km/h',
    weatherSummaryHumidity: '湿度 {value}%',
    weatherSummaryUv: '紫外线 {value}',
    weatherSummaryBasedOnForecast: '基于天气预报',
    weatherTipsForDate: '{date} 打包建议',
    weatherTipMustPrefix: '必带：',
    weatherTipOptionalPrefix: '建议：',
    createTripTitle: '新建行程',
    tripNameLabel: '名称',
    tripNamePlaceholder: '例如：海边两日游…',
    tripDateTimeLabel: '出发日期与时间',
    tripDateStart: '出发时间',
    tripDateEnd: '返程时间（选填）',
    tripEndBeforeStartError: '请先填写出发时间，返程时间不能早于出发时间。',
    tripChecklistLabel: '清单',
    tripMustBring: '必带',
    tripOptional: '可选',
    tripAddMustPlaceholder: '添加必带项…',
    tripAddOptionalPlaceholder: '添加可选项…',
    detailEditItem: '编辑物品',
    detailManageListHint: '在下方添加、编辑或删除物品。',
    tripItemsCount: '{count} 项',
    tripStartPastError: '行程开始时间不能早于当前时间。',
    commonCancel: '取消',
    commonSave: '保存',
    commonDelete: '删除',
    myLibraryTitle: '我的',
    myLibrarySubtitle: '行程与资料',
    segmentTrips: '行程',
    segmentHistory: '历史',
    segmentFriends: '好友',
    yourTripsTitle: '我的行程',
    newTripBtn: '+ 新建行程',
    select: '选择',
    selectedCount: '已选 {selected} / {total}',
    deleteSelected: '删除所选',
    deleteSelectedConfirmTitle: '删除已选行程？',
    deleteSelectedConfirmMsg: '将删除 {count} 个已选行程，此操作不可撤销。',
    deleteTripConfirmTitle: '删除这个行程？',
    cannotUndo: '此操作不可撤销。',
    createCustomTripTitle: '创建行程',
    createCustomTripDesc: '从零开始搭建你的打包清单。',
    frequentlyUsed: '常用行程',
    noFrequentTrips: '还没有常用行程',
    noFrequentTripsDesc: '完成几次打包后，这里会显示你的常用行程。',
    clearAll: '全部清空',
    clearHistoryTitle: '清空全部历史？',
    clearHistoryMsg: '将删除该账号下全部打包历史，此操作不可撤销。',
    noHistoryYet: '暂无历史记录',
    noHistoryHint: '完成一次打包后会显示在这里。',
    doneTag: '已完成',
    reuse: '复用',
    deleteHistoryEntry: '删除历史记录',
    friendsSectionTitle: '好友（Checkmate 账号）',
    friendsSectionHint: '输入对方的登录用户名。对方接受后才能共享清单。',
    enterUsername: '请输入用户名。',
    requestSent: '请求已发送。',
    friendRequestSend: '发送好友请求',
    incomingRequestExists: '对方已向你发出请求，可在下方直接接受。',
    requestFailed: '操作失败。',
    lookingUp: '查询中…',
    noSuchUser: '未找到该用户名。',
    acceptPendingQuestion: '接受对方待处理的请求？',
    accept: '接受',
    incomingRequests: '收到的请求',
    decline: '拒绝',
    outgoingRequests: '等待对方处理',
    friendsCount: '好友（{count}）',
    noFriendsYet: '还没有好友',
    friendLabel: '好友',
    noFriendsHint: '在上方输入对方的 Checkmate 用户名发送请求，对方接受后会显示在这里。',
    online: '在线',
    removeFriend: '移除好友',
    removeFriendTitle: '移除好友？',
    removeFriendHint: '移除后会解除共享关系，分配给对方的物品会回到你名下。',
    remove: '移除',
    pleaseWaitText: '请稍候…',
    sharedBy: '共享自',
    assignItem: '分配物品',
    packedProgress: '已打包 {checked} / {total}',
    assignHint: '点击每行右侧头像，可选择由谁来准备该物品。',
    criticalLabel: '重要物品',
    normalLabel: '其他物品',
    finishReady: '全部打包完成，出发！',
    finishNeedCritical: '请先完成重要物品',
    viewOnlyHint: '仅所有者可勾选物品。你当前是只读查看。',
    shareOnServer: '在服务器中共享',
    shareOnServerHint: '输入好友的 Checkmate 登录名。对方需先接受好友请求。',
    shareAllowEditTitle: '允许共同编辑',
    shareAllowEditHint: '开启后，对方可以编辑此行程的物品清单。',
    sharedWithTitle: '已共享给',
    sharePermissionView: '只读',
    sharePermissionEdit: '可编辑',
    shareUsernamePlaceholder: '例如：alex_travels',
    checkingUsername: '正在检查用户名…',
    noAccountWithUsername: '该用户名不存在。',
    yourFriends: '你的好友',
    share: '共享',
    couldNotShare: '共享失败。',
    peopleOnThisList: '此清单成员',
    peopleOnThisListHint: '先从好友中添加成员，再把物品分配给他们。',
    addFriendsFirst: '请先在“我的”页添加好友，再回来继续。',
    add: '添加',
    done: '完成',
    whoPacksThis: '谁来准备这个？',
    addPeopleBeforeAssign: '请先通过共享按钮添加成员，再分配物品。',
    revoke: '撤销',
    couldNotRevokeShare: '无法取消共享。',
    askAnything: '随便问我打包相关问题…',
    assistantTitle: '打包助手',
    assistantSmartHints: '智能建议',
    assistantThinking: '思考中…',
    assistantCurrentAi: '当前 AI：{name}。',
    assistantNoKeyHint: '服务器未配置 AI 密钥，当前仅提供离线建议。',
    aiImportDefaultTripName: 'AI 生成行程 {date}',
    assistantOfflineFallbackHint: '— 离线兜底（云端错误：{hint}）',
    scenarioNotFound: '未找到该行程，请返回重试。',
    goBack: '返回',
    title: '设置',
    accountCenter: '账号中心',
    signedIn: '已登录',
    edit: '编辑',
    general: '通用',
    generalHint: '通知、声音、定位等设置',
    personalization: '个性化',
    personalizationHint: '主题颜色与外观设置',
    accountSecurity: '账号安全',
    accountSecurityHint: '密码修改与账号安全',
    openSection: '进入',
    loadingPrefs: '正在同步设置…',
    notifications: '通知',
    sounds: '声音',
    autoLocation: '自动定位',
    language: '语言',
    langChinese: '中文',
    langEnglish: '英文',
    darkMode: '深色模式',
    themeColor: '主题颜色',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    passwordMismatch: '两次输入的密码不一致。',
    passwordUpdated: '密码更新成功。',
    passwordSaveError: '暂时无法更新密码，请稍后重试。',
    updatePassword: '更新密码',
    dangerous: '危险操作',
    deleteAccountHint: '删除账号后无法恢复。',
    deleteConfirmLabel: '请输入 DELETE 以确认',
    deleteConfirmPlaceholder: 'DELETE',
    deleteMismatch: '确认文本不匹配。',
    deleteAccountButton: '删除账号',
    serverStatus: '服务器状态',
    serverOk: '在线',
    serverFail: '离线',
    logOut: '退出登录',
    displayName: '显示名称',
    displayNameHint: '会展示给好友和共享行程成员。',
    avatarStyle: '头像风格',
    placeholder: '输入显示名称',
    cancel: '取消',
    save: '保存',
    savingProfile: '保存中…',
    displayNameSaveError: '暂时无法保存资料，请稍后重试。',
    notifDenied: '浏览器已阻止通知权限，请前往浏览器设置开启。',
    pickLanguage: '选择语言',
    close: '关闭',
  },
};

export function uiT(lang) {
  const L = lang === 'zh' ? UI_COPY.zh : UI_COPY.en;
  return (key) => L[key] || UI_COPY.en[key] || key;
}

